 # [START runtime]
runtime: python
env: flex
# entrypoint: daphne mlg.asgi:application --bind 0.0.0.0 --port $PORT --verbosity 1
entrypoint: gunicorn -b :$PORT mlg.wsgi
threadsafe: yes

automatic_scaling:
  max_num_instances: 100

runtime_config:
  python_version: 3.8
# [END runtime]